### ISSUE TITLE
Error: export default key value not supported: filters

### ISSUE THREAD

**Issue by leon-fong** [tjk/vue-o2c#5]
Maybe "filters" could be replaced with "computed"

reference: [Vue 3 Migration Guide | filters](https://v3-migration.vuejs.org/breaking-changes/filters.html)

**Comment by tjk** [comment]
Even though this one involves some template transformation, a naive version seems quite doable! Will see if I can try it later today. Thanks for reporting!

**Comment by tjk** [comment]
Took a first stab at it in https://github.com/tjk/vue-o2c/commit/fca333f86d8b80c567d6e1ec6ba3d894036bacff and published v0.1.18.

Thanks again for reporting!
