### ISSUE TITLE
repository for the demo?

### ISSUE THREAD

**Issue by vesper8** [tjk/vue-o2c#7]
First of all thanks a lot for making this and for continuing to improve it! I've been using it and it's been very helpful and time saving!

I really like your GUI demo and would like to run it locally so I can easily paste in code and get the conversion output.

Is it possible you could share the repository for the demo you have https://tjk.github.io/vue-o2c/ please?

Many thanks!!

**Comment by tjk** [comment]
The demo code is in the [docs folders](https://github.com/tjk/vue-o2c/tree/master/docs). Cheers :)
